import request from './request'
import mockRequest from './mockRequest'

export const reqCateGoryList = () => request({ url: '/product/getBaseCategoryList', method: 'get' })
export const reqBannerList = () => mockRequest({ url: '/banner', method: 'get' })
export const reqFloorList = () => mockRequest({ url: '/floor', method: 'get' })
export const reqSearchList = (params) => request({ url: '/list', method: 'post', data: params })
export const reqDetailList = (skuId) => request({ url: `/item/${skuId}`, method: 'get' })
export const reqAddToCart = (skuId, skuNum) => request({ url: `/cart/addToCart/${skuId}/${skuNum}`, method: 'post' })
export const reqShopCart = () => request({ url: '/cart/cartList', mothod: 'get' })
export const reqCheckCart = (skuID, isChecked) => request({ url: `/cart/checkCart/${skuID}/${isChecked}`, method: 'get' })
export const reqDeleteCart = (skuId) => request({ url: `/cart/deleteCart/${skuId}`, method: 'delete' })
export const reqRegister = (data) => request({ url: '/user/passport/register', method: 'post', data })
export const reqGetCode = (phone) => request({ url: `/user/passport/sendCode/${phone}`, method: 'get' })
export const reqLogin = (data) => request({ url: '/user/passport/login', method: 'post', data })
export const reqUserInfo = () => request({ url: '/user/passport/auth/getUserInfo', method: 'get' })
export const reqLoginout = () => request({ url: '/user/passport/logout', method: 'get' })
export const reqUserAddress = () => request({ url: '/user/userAddress/auth/findUserAddressList', method: 'get' })
export const reqOrderTrade = () => request({ url: '/order/auth/trade', method: 'get' })
export const reqSubmitOrder = (tradeNo, data) => request({ url: `/order/auth/submitOrder?tradeNo=${tradeNo}`, method: 'post', data })
export const reqPayment = (orderId) => request({ url: `/payment/weixin/createNative/${orderId}`, method: 'get' })
export const reqQueryPayStatus = (orderId) => request({ url: `/payment/weixin/queryPayStatus/${orderId}`, method: 'get' })
export const reqOrder = (page, limit) => request({ url: `/order/auth/${page}/${limit}`, method: 'get' })
